extends Node

var characters: Array[Dictionary] = [
	{
		"id": 0,
		"key": "character_a",
		"name": "Block Titan",
		"texture": "res://Assets/Models/KennyBlockyCharacters/Models/FBX format/Textures/texture-a.png",
		"icon": "res://Assets/UI/CharacterIcons/1.jpg",
		"attack": "90",
		"defense": "85",
		"speed": "70",
		"special": "85",
		"special_name": "Earthquake",
		"special_desc": "Ground slam shockwave",
		"special_type": "ground_smash"
	},
	{
		"id": 1,
		"key": "character_b",
		"name": "Iron Brawler",
		"texture": "res://Assets/Models/KennyBlockyCharacters/Models/FBX format/Textures/texture-b.png",
		"icon": "res://Assets/UI/CharacterIcons/2.jpg",
		"attack": "75",
		"defense": "92",
		"speed": "65",
		"special": "70",
		"special_name": "Iron Guard",
		"special_desc": "Hardens skin & blocks dmg",
		"special_type": "shield"
	},
	{
		"id": 2,
		"key": "character_c",
		"name": "Shadow Striker",
		"texture": "res://Assets/Models/KennyBlockyCharacters/Models/FBX format/Textures/texture-c.png",
		"icon": "res://Assets/UI/CharacterIcons/3.jpg",
		"attack": "80",
		"defense": "68",
		"speed": "90",
		"special": "85",
		"special_name": "Shadow Dash",
		"special_desc": "Teleports behind opponent",
		"special_type": "teleport"
	},
	{
		"id": 3,
		"key": "character_d",
		"name": "Crimson Boxer",
		"texture": "res://Assets/Models/KennyBlockyCharacters/Models/FBX format/Textures/texture-d.png",
		"icon": "res://Assets/UI/CharacterIcons/4.jpg",
		"attack": "88",
		"defense": "75",
		"speed": "78",
		"special": "92",
		"special_name": "Fireball",
		"special_desc": "Explosive fiery projectile",
		"special_type": "fireball"
	},
	{
		"id": 4,
		"key": "character_e",
		"name": "Volt Crusher",
		"texture": "res://Assets/Models/KennyBlockyCharacters/Models/FBX format/Textures/texture-e.png",
		"icon": "res://Assets/UI/CharacterIcons/5.jpg",
		"attack": "84",
		"defense": "72",
		"speed": "86",
		"special": "90",
		"special_name": "Lightning Bolt",
		"special_desc": "Calls sky electric strike",
		"special_type": "lightning"
	},
	{
		"id": 5,
		"key": "character_f",
		"name": "Cyber Champ",
		"texture": "res://Assets/Models/KennyBlockyCharacters/Models/FBX format/Textures/texture-f.png",
		"icon": "res://Assets/UI/CharacterIcons/6.jpg",
		"attack": "82",
		"defense": "80",
		"speed": "80",
		"special": "88",
		"special_name": "Laser Blast",
		"special_desc": "High-energy beam cannon",
		"special_type": "laser"
	},
	{
		"id": 6,
		"key": "character_g",
		"name": "Thunder Punch",
		"texture": "res://Assets/Models/KennyBlockyCharacters/Models/FBX format/Textures/texture-g.png",
		"icon": "res://Assets/UI/CharacterIcons/7.jpg",
		"attack": "92",
		"defense": "82",
		"speed": "68",
		"special": "80",
		"special_name": "Thunder Smash",
		"special_desc": "Charged electric ground slam",
		"special_type": "ground_smash"
	},
	{
		"id": 7,
		"key": "character_h",
		"name": "Steel Guard",
		"texture": "res://Assets/Models/KennyBlockyCharacters/Models/FBX format/Textures/texture-h.png",
		"icon": "res://Assets/UI/CharacterIcons/8.jpg",
		"attack": "70",
		"defense": "95",
		"speed": "60",
		"special": "85",
		"special_name": "Self Heal",
		"special_desc": "Restores +60 HP instantly",
		"special_type": "heal"
	},
	{
		"id": 8,
		"key": "character_i",
		"name": "Ghost Boxer",
		"texture": "res://Assets/Models/KennyBlockyCharacters/Models/FBX format/Textures/texture-i.png",
		"icon": "res://Assets/UI/CharacterIcons/9.jpg",
		"attack": "78",
		"defense": "65",
		"speed": "92",
		"special": "88",
		"special_name": "Frost Spike",
		"special_desc": "Freezes target in ice",
		"special_type": "freeze"
	},
	{
		"id": 9,
		"key": "character_j",
		"name": "Blaze Fighter",
		"texture": "res://Assets/Models/KennyBlockyCharacters/Models/FBX format/Textures/texture-j.png",
		"icon": "res://Assets/UI/CharacterIcons/10.jpg",
		"attack": "86",
		"defense": "74",
		"speed": "82",
		"special": "94",
		"special_name": "Inferno Blast",
		"special_desc": "Launches burning fireball",
		"special_type": "fireball"
	},
	{
		"id": 10,
		"key": "character_k",
		"name": "Neon Warrior",
		"texture": "res://Assets/Models/KennyBlockyCharacters/Models/FBX format/Textures/texture-k.png",
		"icon": "res://Assets/UI/CharacterIcons/11.jpg",
		"attack": "80",
		"defense": "78",
		"speed": "85",
		"special": "84",
		"special_name": "Blast Shot",
		"special_desc": "Fires rapid projectile shot",
		"special_type": "gunfire"
	},
	{
		"id": 11,
		"key": "character_l",
		"name": "Vortex Master",
		"texture": "res://Assets/Models/KennyBlockyCharacters/Models/FBX format/Textures/texture-l.png",
		"icon": "res://Assets/UI/CharacterIcons/12.jpg",
		"attack": "82",
		"defense": "76",
		"speed": "88",
		"special": "86",
		"special_name": "Tornado Spin",
		"special_desc": "Whirlwind multi-strike",
		"special_type": "tornado"
	},
	{
		"id": 12,
		"key": "character_m",
		"name": "Solar Knight",
		"texture": "res://Assets/Models/KennyBlockyCharacters/Models/FBX format/Textures/texture-m.png",
		"icon": "res://Assets/UI/CharacterIcons/13.jpg",
		"attack": "85",
		"defense": "82",
		"speed": "75",
		"special": "88",
		"special_name": "Solar Flare",
		"special_desc": "Piercing laser ray blast",
		"special_type": "laser"
	},
	{
		"id": 13,
		"key": "character_n",
		"name": "Glitch Boxer",
		"texture": "res://Assets/Models/KennyBlockyCharacters/Models/FBX format/Textures/texture-n.png",
		"icon": "res://Assets/UI/CharacterIcons/14.jpg",
		"attack": "79",
		"defense": "70",
		"speed": "94",
		"special": "90",
		"special_name": "Phase Shift",
		"special_desc": "Teleports behind opponent",
		"special_type": "teleport"
	},
	{
		"id": 14,
		"key": "character_o",
		"name": "Plasma Gunner",
		"texture": "res://Assets/Models/KennyBlockyCharacters/Models/FBX format/Textures/texture-o.png",
		"icon": "res://Assets/UI/CharacterIcons/15.jpg",
		"attack": "84",
		"defense": "76",
		"speed": "82",
		"special": "90",
		"special_name": "Plasma Shot",
		"special_desc": "High velocity gun round",
		"special_type": "gunfire"
	},
	{
		"id": 15,
		"key": "character_p",
		"name": "Frost Bruiser",
		"texture": "res://Assets/Models/KennyBlockyCharacters/Models/FBX format/Textures/texture-p.png",
		"icon": "res://Assets/UI/CharacterIcons/16.jpg",
		"attack": "83",
		"defense": "84",
		"speed": "72",
		"special": "88",
		"special_name": "Ice Freeze",
		"special_desc": "Freezes target in ice block",
		"special_type": "freeze"
	},
	{
		"id": 16,
		"key": "character_q",
		"name": "Toxic Brawler",
		"texture": "res://Assets/Models/KennyBlockyCharacters/Models/FBX format/Textures/texture-q.png",
		"icon": "res://Assets/UI/CharacterIcons/17.jpg",
		"attack": "86",
		"defense": "78",
		"speed": "76",
		"special": "86",
		"special_name": "Poison Orb",
		"special_desc": "Toxic gas projectile cloud",
		"special_type": "fireball"
	},
	{
		"id": 17,
		"key": "character_r",
		"name": "Golden Champion",
		"texture": "res://Assets/Models/KennyBlockyCharacters/Models/FBX format/Textures/texture-r.png",
		"icon": "res://Assets/UI/CharacterIcons/18.jpg",
		"attack": "88",
		"defense": "88",
		"speed": "80",
		"special": "95",
		"special_name": "Vitality Surge",
		"special_desc": "Heals +75 HP instantly",
		"special_type": "heal"
	}
]

var player1_character: Dictionary = {}
var player2_character: Dictionary = {}
